### ISSUE TITLE
Extension doesn't work with Edge? (Not sure if it is supposed to, but I think it should)

### ISSUE THREAD

**Issue by ryanjakecherian** [jotraverso/chrome-desktop-outlook-notifier#1]
It uploads successfully, and is active because the icon is active when on outlook.office365.com but i still dont get notifications :(

**Comment by jotraverso** [comment]
I'm currently using with MS Edge with MacOs and Chrome.

Note the manifest is configured for https://*.office365.com/* and https://*.office.com/*

Catalina
10.15.7 (19H524)

MS Edge
Version 88.0.705.74 (Official build) (64-bit)

Chrome
Version 88.0.4324.182 (Official Build) (x86_64)
